spring.application.name=jobapplicationbackend

spring.datasource.url=jdbc:h2:file:C:/Users/Sachin/SACHIN/Study/Web_Dev/Java_Development/Backend_Projects/jobapplicationdb;AUTO_SERVER=true

spring.datasource.username=sa
spring.datasource.password=
#spring.sql.init.mode=always
spring.datasource.driver-class-name=org.h2.Driver